[tox]
envlist=
    py310-django51,
    py311-django{51,52},
    py312-django{51,52,60},
    py313-django{52,60},
    coverage,
    docs,

[testenv]
deps = django-polymorphic
    django51: Django>=5.1,<5.2
    django52: Django>=5.2,<5.3
    django60: Django>=6.0,<6.1
    django-dev: https://github.com/django/django/tarball/main
commands=
    python runtests.py

[testenv:docs]
deps =
	Sphinx
	sphinx_rtd_theme
	-r{toxinidir}/docs/_ext/djangodummy/requirements.txt
changedir = docs
commands = sphinx-build -W -b html -d {envtmpdir}/doctrees . {envtmpdir}/html

[testenv:coverage]
basepython=python3.12
deps=
    django>=5.2,<5.3
    coverage
commands=
    coverage erase
    coverage run --source=example/article,parler runtests.py
    coverage report
