
on:
  pull_request: 
  push:
    branches:
      - master

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to TestPyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://test.pypi.org/p/django-parler
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python 3.13
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Install gettext
      run: apt get install gettext
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .

    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        skip_existing: true
